import Head from 'next/head'
import TopTable from '../components/cmc-table/TopTenTable'
import Header from '../components/Header'
import Trending from '../components/Trending'

const styles = {
  wrapper: 'w-screen h-screen flex flex-col',
  example : '',
}

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* trendings */}
      <Trending /> 
      {/* CNC table */}
      <TopTable />
    </div>
  )
}
