import Head from 'next/head'
import Header from '../components/Header'

const styles = {
  wrapper: 'w-screen h-screen flex flex-col',
  example : '',
}

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* trendings */}
      {/* CNC table */}
    </div>
  )
}
